### ISSUE TITLE
index.html is missing

### ISSUE THREAD

**Issue by abodacs** [pavelloz/webpack-tailwindcss#8]
I can't find the file index.html, I think it is missing

**Comment by pavelloz** [comment]
Ouh, you are right! Probably i missed it with gitignore or something.
Fix is on the way!

Soon ill migrate it to use html plugin so its more modern and less "scripty".

**Comment by pavelloz** [comment]
There it is: https://github.com/pavelloz/webpack-tailwindcss/blob/master/app/index.html

**Comment by pavelloz** [comment]
I also added some more content to it, to showcase of whats included:
![image](https://user-images.githubusercontent.com/546845/153919367-c2cc3639-fefb-44ab-bf8c-52f9981d6ae7.png)
